# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation de java (JDK 1.8)
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Générer le jar du projet
      run: mvn -B package --file pom.xml
    - name: PWD
      run: ls -rtl target 
    
    - name: Construire et pousser l'image docker vers le Docker Hub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sergekouassi/spring-greeting
        tags: 1.0.1
        tag_with_ref: true
        tag_with_sha: true
    
    - name: Démarrage / Redémarrage du conteneur docker sur le Serveur AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_AWS }}
        username: ${{ secrets.USER_AWS }}
        key: ${{ secrets.KEY_AWS }}
        port: ${{ secrets.PORT_AWS }}
        script: |
          sudo docker stop serge-greeting
          sudo docker run -d --rm --name serge-greeting -p 8082:8080 sergekouassi/spring-greeting:1.0.1
          sudo docker ps
