# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation de java (JDK 1.8)
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Générer le jar du projet
      run: mvn -B package --file pom.xml
    - name: PWD
      run: pwd & ls -rtl
    - name: Copie du fichier sur le serveur AWS
      uses: appleboy/scp-action@master
      with:
        host: 3.18.101.107
        username: ${{ secrets.USER_AWS }}
        port: 22
        key: ${{ secrets.KEY_AWS }}
        source: "/home/runner/work/cicd-application/cicd-application/target"
        target: "/usr/webservices"
